In [1]:
# CELL 1 — Imports & config
import pandas as pd
import os

BASE_PATH   = r"C:\Users\Lenovo\Downloads\nyc_taxi_project"
SILVER_PATH = os.path.join(BASE_PATH, "silver", "yellow_trips_silver.parquet")
GOLD_DIR    = os.path.join(BASE_PATH, "gold")

os.makedirs(GOLD_DIR, exist_ok=True)

In [2]:
# CELL 2 — Load Silver
df = pd.read_parquet(SILVER_PATH)
print(f"Silver records loaded: {len(df):,}")

Silver records loaded: 2,883,081

In [3]:
# CELL 3 — Gold Table 1: Hourly stats
gold_hourly = (df
    .groupby("pickup_hour")
    .agg(
        total_trips       = ("pickup_hour", "count"),
        avg_fare          = ("fare_amount", "mean"),
        avg_duration_mins = ("trip_duration_minutes", "mean"),
        avg_tip_pct       = ("tip_percentage", "mean"),
        total_revenue     = ("total_amount", "sum")
    )
    .round(2)
    .reset_index()
    .sort_values("pickup_hour")
)
print("Hourly Stats:")
display(gold_hourly)

Hourly Stats:

,pickup_hour,total_trips,avg_fare,avg_duration_mins,avg_tip_pct,total_revenue
0,0,79531,19.79,15.67,20.42,2295238.95
1,1,55528,17.82,14.90,20.96,1460272.16
2,2,38701,16.70,14.66,20.72,959300.15
3,3,25028,17.72,14.59,20.26,650732.50
4,4,15806,22.18,15.81,17.99,496456.57
5,5,16128,26.43,15.70,16.57,590591.94
6,6,39923,22.13,15.16,18.12,1220036.55
7,7,79518,18.90,15.14,37.66,2130970.69
8,8,107864,17.42,15.70,20.02,2709190.80
9,9,122596,17.60,15.34,19.91,3127041.51
10,10,135231,17.71,15.35,19.52,3460184.66
11,11,145225,17.40,15.21,19.49,3656425.11
12,12,160181,17.74,15.44,19.51,4104580.28
13,13,168712,18.46,16.25,19.38,4467756.92
14,14,180942,19.75,17.70,19.27,5088723.81
15,15,185402,19.28,17.69,19.36,5094431.88
16,16,184600,19.53,17.72,21.78,5475079.16
17,17,197141,18.61,17.00,21.89,5650331.57
18,18,203543,16.97,15.27,22.51,5436256.13
19,19,182624,17.64,14.60,22.40,5024594.87
20,20,157322,18.02,14.33,22.87,4254481.91
21,21,153326,18.50,14.36,21.76,4238995.51
22,22,139911,19.39,15.09,21.16,4004334.82
23,23,108298,20.58,15.42,20.63,3251781.73

In [4]:
# CELL 4 — Gold Table 2: Daily revenue
gold_daily = (df
    .groupby("pickup_date")
    .agg(
        total_trips        = ("pickup_date", "count"),
        daily_revenue      = ("total_amount", "sum"),
        avg_fare           = ("fare_amount", "mean"),
        avg_distance_miles = ("trip_distance_miles", "mean"),
        avg_duration_mins  = ("trip_duration_minutes", "mean")
    )
    .round(2)
    .reset_index()
    .sort_values("pickup_date")
)
print("Daily Revenue:")
display(gold_daily)

Daily Revenue:

,pickup_date,total_trips,daily_revenue,avg_fare,avg_distance_miles,avg_duration_mins
0,2008-12-31,1,80.55,70.00,17.76,927.48
1,2022-10-25,4,159.20,37.25,2.45,6.87
2,2022-12-31,25,658.23,16.63,3.31,12.21
3,2023-01-01,69968,2156065.54,21.94,4.38,17.54
4,2023-01-02,61858,1946192.83,22.31,4.64,16.41
5,2023-01-03,80528,2371351.96,20.25,3.94,16.60
6,2023-01-04,89510,2521817.48,19.17,3.60,16.32
7,2023-01-05,95164,2605814.42,18.51,3.43,16.09
8,2023-01-06,96600,2582506.63,17.94,3.26,15.55
9,2023-01-07,99147,2546027.64,17.72,3.28,14.95
10,2023-01-08,80133,2293951.79,19.94,4.02,14.94
11,2023-01-09,80049,2256058.46,19.04,3.65,15.43
12,2023-01-10,94304,2512816.25,17.80,3.21,15.06
13,2023-01-11,100153,2643595.05,17.56,3.16,15.21
14,2023-01-12,104426,2894574.41,18.57,3.34,16.56
15,2023-01-13,104101,2937721.99,18.86,3.48,16.57
16,2023-01-14,106531,2789702.99,17.97,3.26,15.62
17,2023-01-15,91094,2483191.25,18.82,3.63,14.92
18,2023-01-16,75476,2194072.55,20.06,4.05,15.49
19,2023-01-17,95046,2679053.72,18.92,3.48,16.06
20,2023-01-18,100132,2730779.66,18.22,3.24,16.00
21,2023-01-19,107344,2896136.47,18.03,3.06,16.90
22,2023-01-20,103161,2791923.15,18.10,3.24,16.17
23,2023-01-21,105650,2640434.90,17.13,3.07,14.78
24,2023-01-22,84218,2333915.46,19.12,3.75,15.08
25,2023-01-23,84225,2313769.86,18.40,3.45,15.04
26,2023-01-24,97883,2599128.29,17.65,3.11,15.47
27,2023-01-25,102121,2654617.58,17.21,2.94,15.74
28,2023-01-26,108033,2953019.91,18.23,3.23,16.24
29,2023-01-27,105179,2835029.36,17.94,3.20,16.13
30,2023-01-28,105124,2638903.26,17.21,3.01,15.60
31,2023-01-29,82815,2299999.89,19.17,3.75,15.07
32,2023-01-30,78627,2202289.66,18.86,3.56,15.65
33,2023-01-31,94441,2542115.98,18.04,3.08,16.23
34,2023-02-01,10,313.81,22.02,4.57,14.68

In [5]:
# CELL 5 — Gold Table 3: Payment breakdown
gold_payment = (df
    .groupby("payment_type_label")
    .agg(
        total_trips   = ("payment_type_label", "count"),
        avg_tip_pct   = ("tip_percentage", "mean"),
        total_revenue = ("total_amount", "sum")
    )
    .round(2)
    .reset_index()
    .sort_values("total_trips", ascending=False)
)
print("Payment Breakdown:")
display(gold_payment)

Payment Breakdown:

  payment_type_label  total_trips  avg_tip_pct  total_revenue
1        Credit Card      2350156        25.97    66246302.91
0               Cash       507711         0.00    12008731.60
2            Dispute        16220         0.14      389905.56
3          No Charge         8994         0.02      202850.11

In [6]:
# CELL 6 — Gold Table 4: Top 10 busiest zones
gold_zones = (df
    .groupby("pickup_location_id")
    .agg(
        total_pickups = ("pickup_location_id", "count"),
        avg_fare      = ("fare_amount", "mean"),
        avg_distance  = ("trip_distance_miles", "mean")
    )
    .round(2)
    .reset_index()
    .sort_values("total_pickups", ascending=False)
    .head(10)
)
print("Top 10 Busiest Zones:")
display(gold_zones)

Top 10 Busiest Zones:

     pickup_location_id  total_pickups  avg_fare  avg_distance
122                 132         151975     60.72         15.51
225                 237         141096     12.35          1.80
224                 236         130870     13.13          1.97
151                 161         129081     15.26          2.39
175                 186         104793     15.55          2.32
152                 162         100785     14.89          2.36
132                 142          94899     13.60          2.19
218                 230          94196     17.38          2.99
128                 138          86720     41.49          9.68
160                 170          83972     14.83          2.32

In [7]:
# CELL 7 — Save all Gold tables as CSV
gold_tables = {
    "hourly_stats"      : gold_hourly,
    "daily_revenue"     : gold_daily,
    "payment_breakdown" : gold_payment,
    "top_zones"         : gold_zones,
}

for name, table in gold_tables.items():
    path = os.path.join(GOLD_DIR, f"{name}.csv")
    table.to_csv(path, index=False)
    print(f"Saved: {path}")

print("\nPipeline complete! Bronze -> Silver -> Gold")
print(f"Your CSVs are in: {GOLD_DIR}")

Saved: C:\Users\Lenovo\Downloads\nyc_taxi_project\gold\hourly_stats.csv
Saved: C:\Users\Lenovo\Downloads\nyc_taxi_project\gold\daily_revenue.csv
Saved: C:\Users\Lenovo\Downloads\nyc_taxi_project\gold\payment_breakdown.csv
Saved: C:\Users\Lenovo\Downloads\nyc_taxi_project\gold\top_zones.csv

Pipeline complete! Bronze -> Silver -> Gold
Your CSVs are in: C:\Users\Lenovo\Downloads\nyc_taxi_project\gold